### ISSUE TITLE
apt-get upgrade fails - problems with udev

### ISSUE THREAD

**Issue by nshanny** [Microsoft/BashOnWindows#143]
I have completely uninstalled and reinstalled and continue to receive the following errors:

root@localhost:/var# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - openpty (2: No such file or directory)
Setting up udev (204-5ubuntu20.19) ...
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: No such file or directory
runlevel:/var/run/utmp: No such file or directory
 * udev requires devtmpfs support, not started
   ...fail!
invoke-rc.d: initscript udev, action "restart" failed.
dpkg: error processing package udev (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of systemd-services:
 systemd-services depends on udev (>= 175-0ubuntu23); however:
  Package udev is not configured yet.

dpkg: error processing package systemd-services (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpam-systemd:amd64:
No apport report written because the error message indicates its a followup error from a previous failure. libpam-systemd:amd64 depends on systemd-services (= 204-5ubuntu20.19); however:

  Package systemd-services is not configured yet.

dpkg: error processing package libpam-systemd:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of initramfs-tools:
No apport report written because the error message indicates its a followup error from a previous failure. initramfs-tools depends on udev (>= 147~-5); however:

  Package udev is not configured yet.

dpkg: error processing package initramfs-tools (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 udev
 systemd-services
 libpam-systemd:amd64
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mindleak** [comment]
I am having this identical issue.

**Comment by plessbd** [comment]
thought the crash log I got might be useful, also note that I didnt install bash on windows until 2016-04-11 so I am not sure what the 2016-03-23 commands are from

```
root@localhost:/var/crash# cat /var/crash/udev.0.crash
ProblemType: Package
Architecture: amd64
Date: Mon Apr 11 15:09:17 2016
Package: udev 204-5ubuntu20.19
SourcePackage: systemd
ErrorMessage:
 subprocess installed post-installation script returned error exit status 1
DpkgTerminalLog:

 Log started: 2016-03-23  20:54:26
 Log ended: 2016-03-23  20:54:50

 Log started: 2016-04-11  15:03:36
 Log ended: 2016-04-11  15:03:42

 Log started: 2016-04-11  15:08:57

DpkgHistoryLog:

 Start-Date: 2016-03-23  20:54:26
 Commandline: apt-get --purge remove --assume-yes grub-common grub-gfxpayload-lists grub-legacy-ec2 grub-pc grub-pc-bin linux-headers-3.13.0-83 linux-headers-3.13.0-83-generic linux-headers-generic linux-headers-virtual linux-image-3.13.0-83-generic linux-image-virtual linux-virtual
 Purge: grub-gfxpayload-lists:amd64 (0.6), linux-headers-generic:amd64 (3.13.0.83.89), linux-image-3.13.0-83-generic:amd64 (3.13.0-83.127), linux-headers-3.13.0-83-generic:amd64 (3.13.0-83.127), linux-image-virtual:amd64 (3.13.0.83.89), grub-common:amd64 (2.02~beta2-9ubuntu1.7), linux-virtual:amd64 (3.13.0.83.89), linux-headers-virtual:amd64 (3.13.0.83.89), grub2-common:amd64 (2.02~beta2-9ubuntu1.7), grub-legacy-ec2:amd64 (0.7.5-0ubuntu1.17), linux-headers-3.13.0-83:amd64 (3.13.0-83.127), grub-pc-bin:amd64 (2.02~beta2-9ubuntu1.7), grub-pc:amd64 (2.02~beta2-9ubuntu1.7)
 End-Date: 2016-03-23  20:54:50

 Start-Date: 2016-04-11  15:03:36
 Commandline: apt-get install git
 Install: liberror-perl:amd64 (0.17-1.1, automatic), git-man:amd64 (1.9.1-1ubuntu0.3, automatic), git:amd64 (1.9.1-1ubuntu0.3)
 End-Date: 2016-04-11  15:03:42

 Start-Date: 2016-04-11  15:08:57
 Commandline: apt-get upgrade
 Upgrade: apt:amd64 (1.0.1ubuntu2.11, 1.0.1ubuntu2.12), initramfs-tools-bin:amd64 (0.103ubuntu4.2, 0.103ubuntu4.3), libsystemd-login0:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), systemd-services:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), apt-transport-https:amd64 (1.0.1ubuntu2.11, 1.0.1ubuntu2.12), apt-utils:amd64 (1.0.1ubuntu2.11, 1.0.1ubuntu2.12), libsystemd-daemon0:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), libpam-systemd:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), libapt-inst1.5:amd64 (1.0.1ubuntu2.11, 1.0.1ubuntu2.12), udev:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), initramfs-tools:amd64 (0.103ubuntu4.2, 0.103ubuntu4.3), libudev1:amd64 (204-5ubuntu20.18, 204-5ubuntu20.19), libapt-pkg4.12:amd64 (1.0.1ubuntu2.11, 1.0.1ubuntu2.12), tzdata:amd64 (2016b-0ubuntu0.14.04, 2016c-0ubuntu0.14.04), cloud-init:amd64 (0.7.5-0ubuntu1.17, 0.7.5-0ubuntu1.18), libpcre3:amd64 (8.31-2ubuntu2.1, 8.31-2ubuntu2.2)
AptOrdering:
 libapt-pkg4.12: Install
 libapt-pkg4.12: Configure
 apt: Install
 apt: Configure
 libpcre3: Install
 libpcre3: Configure
 libapt-inst1.5: Install
 udev: Install
 libudev1: Install
 libpam-systemd: Install
 systemd-services: Install
 libsystemd-daemon0: Install
 libsystemd-login0: Install
 tzdata: Install
 tzdata: Configure
 apt-utils: Install
 initramfs-tools: Install
 initramfs-tools-bin: Install
 apt-transport-https: Install
 cloud-init: Install
 libapt-inst1.5: Configure
 libudev1: Configure
 udev: Configure
 libsystemd-daemon0: Configure
 systemd-services: Configure
 libpam-systemd: Configure
 libsystemd-login0: Configure
 apt-utils: Configure
 initramfs-tools-bin: Configure
 initramfs-tools: Configure
 apt-transport-https: Configure
 cloud-init: Configure
Dmesg:
Df:
root@localhost:/var/crash#
```
